package com.vathanakmao.libmgmt.test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;

public class DbUtil {
	
	public static Connection getConnection() throws SQLException {
	    Connection conn = null;
	    Properties connectionProps = new Properties();
	    connectionProps.put("user", "root");
	    connectionProps.put("password", "root");
	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/libmgmt", connectionProps);
	    System.out.println("Connected to database");
	    return conn;
	}

	public static void main(String[] args) throws SQLException {
		Connection conn = null;
 
		// An object that represents a precompiled SQL statement.
		PreparedStatement stmt = null;
		try {
			conn = getConnection();
			stmt = conn.prepareStatement("select * from book");
 
			// A table of data representing a database result set, which is
			// usually generated by executing a statement that queries the
			// database.
			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
				System.out.println("Title: " + rs.getString("title"));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			// Close Statement and Connection
			if (stmt != null) {
				stmt.close();
			}
			if (conn != null) {
				conn.close();
			}
		}
	
	}
}
